### ISSUE TITLE
Incorrect minimum Python version

### ISSUE THREAD

**Issue by DManowitz** [conda-forge/argh-feedstock#26]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

This conda-forge package indicates `python >=3` as a dependency.  However, as seen in the [Github repo](https://github.com/neithere/argh/blob/v0.28.0/pyproject.toml), Python 3.8 has been the minimum required version since argh v0.28.0.

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by tschoonj** [comment]
I would happily merge in a PR that addresses this
